ALTER TABLE "Class" ADD COLUMN "displayOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Team" ADD COLUMN "displayOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Album" ADD COLUMN "showOnHome" BOOLEAN NOT NULL DEFAULT false;
