CREATE TYPE "AlbumViewMode" AS ENUM ('SLIDE', 'GRID');

ALTER TABLE "Post" ADD COLUMN "showOnHome" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MemoryPost" ADD COLUMN "showOnHome" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Album" ADD COLUMN "viewMode" "AlbumViewMode" NOT NULL DEFAULT 'SLIDE';
